server:
  port: 9000

spring:
  application:
    name: config-server # Industry standard: kebab-case, lowercase
  profiles:
    active: git # Switched to git profile to fetch configs from GitHub

---
spring:
  config:
    activate:
      on-profile: "native"
  cloud:
    config:
      server:
        native:
          search-locations:
            # Standard formatting using arrays for lists
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services
---
spring:
  config:
    activate:
      on-profile: "git"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LakhiniVoshadee/Capstone-Project-Configurations.git
          search-paths:
            - platform
            - services
          clone-on-start: true # Good practice: Fails fast on startup if git repo is unreachable

